name: Matrix Workflow
on: 
  push:
    branches: develop
jobs:
  node-version:
    runs-on: ubuntu-latest
      steps:
        - name: Log node version
          run: node -v
          - uses: actions/setup-node@v3
            with: 
            node-version: '14'
        - name: Log node version
          run: node -v