name: Shell Commands
on: 
  push:
    branches:
      - master
jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
    - name: echo string
      run: echo "welcome to the world"
    - name: multiline script
      run: |
        node -v
        npm -v
        cat /etc/os-release